name: greetings-german
parent: default

matches:

  - trigger: ",sgdh"
    replace: "Sehr geehrte Dame, Sehr geehrter Herr,\n\n"

  - trigger: ",sgf"
    replace: "Sehr geehrte Frau {{clipboard}},\n\n"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ",sgh"
    replace: "Sehr geehrter Herr {{clipboard}},\n\n"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ",sgt"
    replace: "Sehr geehrtes {{clipboard}}-Team,\n\n"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ",sgdh"
    replace: "Sehr geehrte Dame, Sehr geehrter Herr,\n\n"

  - trigger: ",gm"
    replace: "Guten Morgen,\n\n"

  - trigger: "!mm"
    replace: "Moin, Moin!\n\n"

  - trigger: "!dgg"
    replace: "\nDanke sehr, viele Grüße & alles Gute!"

  - trigger: "!gg"
    replace: "\nViele Grüße & alles Gute!"

  - trigger: ",mfg"
    replace: "\nMit freundlichen Grüßen,\n"

  - trigger: ",vg"
    replace: "\nViele Grüße,\n"

  - trigger: "!ds"
    replace: "\nDanke sehr!"
